export const CONFIG = {
  POINTS_PER_QUESTION: 10,
  TIMER_SECONDS: 15,
  TOTAL_QUESTIONS: 10,
  STREAK_2X_THRESHOLD: 3,
  STREAK_3X_THRESHOLD: 5,
  STREAK_2X_MULTIPLIER: 2,
  STREAK_3X_MULTIPLIER: 3,
};
