export const CONFIG = {
  POINTS_PER_QUESTION: 10,
  TIMER_SECONDS: 15,
  TOTAL_QUESTIONS: 10,
  STREAK_2X_THRESHOLD: 3,
  STREAK_3X_THRESHOLD: 5,
  STREAK_2X_MULTIPLIER: 2,
  STREAK_3X_MULTIPLIER: 3,
  DIFFICULTY: {
    easy: { label: 'Easy', timerSeconds: 20 },
    medium: { label: 'Medium', timerSeconds: 15 },
    hard: { label: 'Hard', timerSeconds: 10 },
  },
  DEFAULT_DIFFICULTY: 'medium',
  THEMES: {
    default: {
      label: 'Classic',
      primary: '#6c5ce7',
      primaryHover: '#5a4bd1',
      correct: '#00b894',
      wrong: '#d63031',
      bg: '#f8f9fa',
      cardBg: '#ffffff',
      text: '#2d3436',
      textLight: '#636e72',
      accent: '#f0eeff',
    },
    ocean: {
      label: 'Ocean',
      primary: '#0984e3',
      primaryHover: '#0770c2',
      correct: '#00b894',
      wrong: '#d63031',
      bg: '#edf5fc',
      cardBg: '#ffffff',
      text: '#1a3a5c',
      textLight: '#5a7fa0',
      accent: '#d6eaf8',
    },
    forest: {
      label: 'Forest',
      primary: '#00a86b',
      primaryHover: '#008f5b',
      correct: '#2ecc71',
      wrong: '#c0392b',
      bg: '#f0f7f4',
      cardBg: '#ffffff',
      text: '#1a3a2a',
      textLight: '#5a7f6a',
      accent: '#d5f0e3',
    },
    sunset: {
      label: 'Sunset',
      primary: '#e17055',
      primaryHover: '#c9604a',
      correct: '#00b894',
      wrong: '#c0392b',
      bg: '#fef5f0',
      cardBg: '#ffffff',
      text: '#3d2017',
      textLight: '#8a6b5e',
      accent: '#fde8df',
    },
    dark: {
      label: 'Dark',
      primary: '#a29bfe',
      primaryHover: '#8c83f0',
      correct: '#55efc4',
      wrong: '#ff7675',
      bg: '#1e1e2e',
      cardBg: '#2a2a3d',
      text: '#e0e0e8',
      textLight: '#a0a0b8',
      accent: '#35354d',
    },
  },
  DEFAULT_THEME: 'default',
};
